const pets = [
    {id: 1, found: false, name: "Rory", type: "Dog", location: "Birmingham", dateLastSeen: "27/03/24", description: "Rory is a adult male german shepherd last seen wearing a red collar.", additionalInformation: "Rory is friendly with people and is safe to approach if spotted. He is frightened of cars and may run when near busy roads. His favourite food is chicken."},
    {id: 2, found: false, name: "Misty", type: "Cat", location: "London", dateLastSeen: "10/05/24", description: "Misty is a medium-sized calico cat with patches of black, orange, and white fur. She has green eyes and a distinctive black spot on her nose.", additionalInformation: "Misty is friendly but may be shy around strangers. She is microchipped but not wearing a collar at the time she went missing. She has a tendency to hide in bushes or under cars when scared."},
    {id: 3, found: false, name: "Lola", type: "Dog", location: "Swansea", dateLastSeen: "13/05/24", description: "Lola is a female golden retriever with a distinctively dark patch of fur around her muzzle area.", additionalInformation: "Lola loves food and often gets herself into troublesome situations trying to find it. She was last seen wearing a pink harness and collar. She is microchipped."},
    {id: 4, found: false, name: "Tyson", type: "Tortoise", location: "Norfolk", dateLastSeen: "28/04/24", description: "Tyson is a 7 year old, medium-sized Hermann tortoise.", additionalInformation: "Tyson lives in an enclosure outside but unfortunately the housesitter forgot to close the latch and he has escaped. He is easily frightened by loud noises and may be found hiding behind your bins or inside outdoor buildings."},
    {id: 5, found: true, name: "Cheddar", type: "Dog", location: "Brighton", dateLastSeen: "07/04/24", description: "Example text.", additionalInformation: "Example text."},
    {id: 6, found: false, name: "Luffy", type: "Cat", location: "Manchester", dateLastSeen: "15/05/24", description: "Luffy is a medium-sized orange tabby cat", additionalInformation: "Luffy is microchipped but was not wearing a collar at the time of going missing. She is friendly with people and tries to get into people's houses for food."},
    {id: 7, found: false, name: "Nibbles", type: "Rabbit", location: "London", dateLastSeen: "03/05/24", description: "X", additionalInformation: "X."},
    {id: 8, found: false, name: "8", type: "X", location: "X", dateLastSeen: "X", description: "X", additionalInformation: "X."},
    {id: 9, found: false, name: "9", type: "X", location: "X", dateLastSeen: "X", description: "X", additionalInformation: "X."},
    {id: 10, found: false, name: "10", type: "X", location: "X", dateLastSeen: "X", description: "X", additionalInformation: "X."},
    {id: 11, found: false, name: "11", type: "X", location: "X", dateLastSeen: "X", description: "X", additionalInformation: "X."},
    {id: 12, found: false, name: "12", type: "X", location: "X", dateLastSeen: "X", description: "X", additionalInformation: "X."},
    {id: 13, found: false, name: "13", type: "X", location: "X", dateLastSeen: "X", description: "X", additionalInformation: "X."},
    {id: 14, found: false, name: "14", type: "X", location: "X", dateLastSeen: "X", description: "X", additionalInformation: "X."},
    {id: 15, found: false, name: "15", type: "X", location: "X", dateLastSeen: "X", description: "X", additionalInformation: "X."},
    {id: 16, found: false, name: "16", type: "X", location: "X", dateLastSeen: "X", description: "X", additionalInformation: "X."},
    {id: 17, found: false, name: "17", type: "X", location: "X", dateLastSeen: "X", description: "X", additionalInformation: "X."},
    {id: 18, found: false, name: "18", type: "X", location: "X", dateLastSeen: "X", description: "X", additionalInformation: "X."},
    {id: 19, found: false, name: "19", type: "X", location: "X", dateLastSeen: "X", description: "X", additionalInformation: "X."},
    {id: 20, found: false, name: "20", type: "X", location: "X", dateLastSeen: "X", description: "X", additionalInformation: "X."},
    {id: 21, found: false, name: "21", type: "X", location: "X", dateLastSeen: "X", description: "X", additionalInformation: "X."},
    {id: 22, found: false, name: "22", type: "X", location: "X", dateLastSeen: "X", description: "X", additionalInformation: "X."},
    {id: 23, found: false, name: "23", type: "X", location: "X", dateLastSeen: "X", description: "X", additionalInformation: "X."},
    {id: 24, found: false, name: "24", type: "X", location: "X", dateLastSeen: "X", description: "X", additionalInformation: "X."},
    {id: 25, found: false, name: "25", type: "X", location: "X", dateLastSeen: "X", description: "X", additionalInformation: "X."},
    {id: 26, found: false, name: "26", type: "X", location: "X", dateLastSeen: "X", description: "X", additionalInformation: "X."},
    {id: 27, found: false, name: "27", type: "X", location: "X", dateLastSeen: "X", description: "X", additionalInformation: "X."}
]

export default pets;
