const pets = [
    {id: 1, found: false, name: "Rory", type: "Dog", location: "Birmingham", dateLastSeen: "27/03/24", description: "Rory is a adult male german shepherd last seen wearing a red collar.", additionalInformation: "Rory is friendly with people and is safe to approach if spotted. He is frightened of cars and may run when near busy roads. His favourite food is chicken.", contactName: "Tyler Jackson", contactEmail: "tylerjackson87@hotmail.com", contactNumber: "07521569034"},
    {id: 2, found: false, name: "Misty", type: "Cat", location: "London", dateLastSeen: "10/05/24", description: "Misty is a medium-sized calico cat with patches of black, orange, and white fur. She has green eyes and a distinctive black spot on her nose.", additionalInformation: "Misty is friendly but may be shy around strangers. She is microchipped but not wearing a collar at the time she went missing. She has a tendency to hide in bushes or under cars when scared.", contactName: "Jane Smith", contactEmail: "jane.smith@example.com", contactNumber: "01234 567890"},
    {id: 3, found: false, name: "Lola", type: "Dog", location: "Swansea", dateLastSeen: "13/05/24", description: "Lola is a female golden retriever with a distinctively dark patch of fur around her muzzle area.", additionalInformation: "Lola loves food and often gets herself into troublesome situations trying to find it. She was last seen wearing a pink harness and collar. She is microchipped.", contactName: "Ahmed Ebhrahim", contactEmail: "skating-places244@aol.com", contactNumber: "07665891245"},
    {id: 4, found: false, name: "Tyson", type: "Tortoise", location: "Norfolk", dateLastSeen: "28/04/24", description: "Tyson is a 7 year old, medium-sized Hermann tortoise.", additionalInformation: "Tyson lives in an enclosure outside but unfortunately the housesitter forgot to close the latch and he has escaped. He is easily frightened by loud noises and may be found hiding behind your bins or inside outdoor buildings.", contactName: "Daphne McDonald", contactEmail: "daphandgav@gmail.com", contactNumber: "07549092144"},
    {id: 5, found: true, name: "Cheddar", type: "Dog", location: "Brighton", dateLastSeen: "07/04/24", description: "Example text.", additionalInformation: "Example text.", contactName: "Name name", contactEmail: "example email", contactNumber: "example number"},
]

export default pets;
