const pets = [
    {id: 1, found: "Lost", name: "Rory", type: "Dog", location: "Birmingham", dateLastSeen: "27/03/24", description: "Rory is an adult male German Shepherd last seen wearing a red collar.", additionalInformation: "Rory is friendly with people and is safe to approach if spotted. He is frightened of cars and may run when near busy roads. His favourite food is chicken."},
    {id: 2, found: "Lost", name: "Misty", type: "Cat", location: "London", dateLastSeen: "10/05/24", description: "Misty is a medium-sized calico cat with patches of black, orange, and white fur. She has green eyes and a distinctive black spot on her nose.", additionalInformation: "Misty is friendly but may be shy around strangers. She is microchipped but not wearing a collar at the time she went missing. She has a tendency to hide in bushes or under cars when scared."},
    {id: 3, found: "Lost", name: "Lola", type: "Dog", location: "Swansea", dateLastSeen: "13/05/24", description: "Lola is a female Golden Retriever with a distinctively dark patch of fur around her muzzle area.", additionalInformation: "Lola loves food and often gets herself into troublesome situations trying to find it. She was last seen wearing a pink harness and collar. She is microchipped."},
    {id: 4, found: "Lost", name: "Tyson", type: "Tortoise", location: "Norfolk", dateLastSeen: "28/04/24", description: "Tyson is a 7-year-old, medium-sized Hermann tortoise.", additionalInformation: "Tyson lives in an enclosure outside but unfortunately the housesitter forgot to close the latch and he has escaped. He is easily frightened by loud noises and may be found hiding behind your bins or inside outdoor buildings."},
    {id: 5, found: "Found", name: "Cheddar", type: "Dog", location: "Brighton", dateLastSeen: "07/04/24", description: "Cheddar is a small Beagle with a tricolor coat. He has a blue collar with a tag.", additionalInformation: "Cheddar is very friendly and loves to play with other dogs. He was found and returned safely to his owner."},
    {id: 6, found: "Lost", name: "Luffy", type: "Cat", location: "Manchester", dateLastSeen: "15/05/24", description: "Luffy is a medium-sized orange tabby cat.", additionalInformation: "Luffy is microchipped but was not wearing a collar at the time of going missing. She is friendly with people and tries to get into people's houses for food."},
    {id: 7, found: "Lost", name: "Nibbles", type: "Rabbit", location: "London", dateLastSeen: "03/05/24", description: "Nibbles is a small, white rabbit with brown spots on her back.", additionalInformation: "Nibbles is very timid and may hide if approached. She enjoys carrots and leafy greens."},
    {id: 8, found: "Lost", name: "Buddy", type: "Dog", location: "Edinburgh", dateLastSeen: "25/04/24", description: "Buddy is a large, black Labrador Retriever with a silver collar.", additionalInformation: "Buddy is very energetic and loves to run. He was last seen near Holyrood Park."},
    {id: 9, found: "Lost", name: "Whiskers", type: "Cat", location: "Glasgow", dateLastSeen: "18/04/24", description: "Whiskers is a small, grey tabby cat with white paws.", additionalInformation: "Whiskers is very affectionate and loves to be petted. She is microchipped and has a pink collar."},
    {id: 10, found: "Lost", name: "Charlie", type: "Dog", location: "Bristol", dateLastSeen: "30/04/24", description: "Charlie is a medium-sized Poodle with curly white fur.", additionalInformation: "Charlie is very friendly and loves to play fetch. He was last seen in the Clifton area."},
    {id: 11, found: "Lost", name: "Bella", type: "Cat", location: "Liverpool", dateLastSeen: "12/05/24", description: "Bella is a large Maine Coon with long, brown fur.", additionalInformation: "Bella is very friendly and enjoys being around people. She is microchipped but was not wearing a collar."},
    {id: 12, found: "Lost", name: "Rocky", type: "Dog", location: "Leeds", dateLastSeen: "02/05/24", description: "Rocky is a small, brown Dachshund with a blue collar.", additionalInformation: "Rocky is very playful and loves to chase balls. He was last seen in the city centre."},
    {id: 13, found: "Lost", name: "Shadow", type: "Cat", location: "Sheffield", dateLastSeen: "05/05/24", description: "Shadow is a medium-sized black cat with bright yellow eyes.", additionalInformation: "Shadow is very shy and may hide if approached. He is microchipped and was last seen near the park."},
    {id: 14, found: "Lost", name: "Molly", type: "Dog", location: "Newcastle", dateLastSeen: "01/05/24", description: "Molly is a large, white Samoyed with a thick fur coat.", additionalInformation: "Molly is very friendly and loves to be around people. She was last seen near the river."},
    {id: 15, found: "Lost", name: "Coco", type: "Cat", location: "Cardiff", dateLastSeen: "04/05/24", description: "Coco is a small, black and white tuxedo cat.", additionalInformation: "Coco is very curious and loves to explore. She is microchipped but was not wearing a collar."},
    {id: 16, found: "Lost", name: "Max", type: "Dog", location: "Belfast", dateLastSeen: "10/05/24", description: "Max is a medium-sized Border Collie with a black and white coat.", additionalInformation: "Max is very energetic and loves to run. He was last seen in the countryside."},
    {id: 17, found: "Lost", name: "Tigger", type: "Cat", location: "Dublin", dateLastSeen: "09/05/24", description: "Tigger is a small, orange tabby cat with white paws.", additionalInformation: "Tigger is very playful and loves to climb trees. He is microchipped but was not wearing a collar."},
    {id: 18, found: "Lost", name: "Buster", type: "Dog", location: "Nottingham", dateLastSeen: "08/05/24", description: "Buster is a large, brindle Boxer with a black collar.", additionalInformation: "Buster is very friendly and loves to play with other dogs. He was last seen in the park."},
    {id: 19, found: "Lost", name: "Simba", type: "Cat", location: "Leicester", dateLastSeen: "07/05/24", description: "Simba is a medium-sized Siamese cat with blue eyes.", additionalInformation: "Simba is very vocal and loves to be around people. He is microchipped but was not wearing a collar."},
    {id: 20, found: "Lost", name: "Peppe", type: "Dog", location: "Coventry", dateLastSeen: "06/05/24", description: "Peppe is a small, furry Jack Russell Terrier.", additionalInformation: "Peppe is very energetic and loves to dig. He was last seen in the garden."},
    {id: 21, found: "Lost", name: "Lily", type: "Cat", location: "Oxford", dateLastSeen: "05/05/24", description: "Lily is a large, fluffy Persian cat with a white coat.", additionalInformation: "Lily is very calm and loves to be petted. She is microchipped and was last seen near the university."},
    {id: 22, found: "Lost", name: "Bruno", type: "Dog", location: "Cambridge", dateLastSeen: "04/05/24", description: "Bruno is a medium-sized Rottweiler with a black and tan coat.", additionalInformation: "Bruno is very loyal and loves to be around his owner. He was last seen near the river."},
    {id: 23, found: "Lost", name: "Socks", type: "Cat", location: "Bath", dateLastSeen: "03/05/24", description: "Socks is a small, grey tabby cat with white paws.", additionalInformation: "Socks is very curious and loves to explore. He is microchipped but was not wearing a collar."},
    {id: 24, found: "Lost", name: "Zoe", type: "Dog", location: "York", dateLastSeen: "02/05/24", description: "Zoe is a large, black Great Dane with a blue collar.", additionalInformation: "Zoe is very gentle and loves to be around people. She was last seen near the city walls."},
    {id: 25, found: "Lost", name: "Oscar", type: "Cat", location: "Chester", dateLastSeen: "01/05/24", description: "Oscar is a small, black cat with a white patch on his chest.", additionalInformation: "Oscar is very shy and may hide if approached. He is microchipped and was last seen near the canal."},
    {id: 26, found: "Lost", name: "Daisy", type: "Dog", location: "Exeter", dateLastSeen: "30/04/24", description: "Daisy is a medium-sized Beagle with a tricolor coat.", additionalInformation: "Daisy is very friendly and loves to sniff around. She was last seen in the countryside."},
    {id: 27, found: "Lost", name: "Ginger", type: "Cat", location: "Norwich", dateLastSeen: "29/04/24", description: "Ginger is a medium-sized, orange tabby cat.", additionalInformation: "Ginger is very affectionate and loves to be petted. He is microchipped but was not wearing a collar."},
    {id: 28, found: "Lost", name: "Tweety", type: "Bird", location: "Bristol", dateLastSeen: "12/05/24", description: "Tweety is a small, yellow budgie.", additionalInformation: "Tweety is very tame and may land on your shoulder. She was last seen near the city centre."},
    {id: 29, found: "Lost", name: "Hoppy", type: "Rabbit", location: "Reading", dateLastSeen: "15/05/24", description: "Hoppy is a medium-sized brown rabbit.", additionalInformation: "Hoppy is very friendly and loves to hop around the garden. She was last seen near the park."},
    {id: 30, found: "Lost", name: "Slinky", type: "Snake", location: "Brighton", dateLastSeen: "08/05/24", description: "Slinky is a small, green garter snake.", additionalInformation: "Slinky is non-venomous and very docile. He was last seen near the garden."},
    {id: 31, found: "Lost", name: "Sheldon", type: "Tortoise", location: "Southampton", dateLastSeen: "10/05/24", description: "Sheldon is a large, 10-year-old African spurred tortoise.", additionalInformation: "Sheldon is very slow and may be found hiding in bushes. He was last seen near the backyard."},
    {id: 32, found: "Lost", name: "Bubbles", type: "Bird", location: "Cambridge", dateLastSeen: "20/05/24", description: "Bubbles is a small blue parakeet with a yellow beak.", additionalInformation: "Bubbles is very tame and might respond to whistling. She was last seen near the city centre."}

];

export default pets;

